### ISSUE TITLE
Typo in "Crypto Wrap-Up" video.

### ISSUE THREAD

**Issue by EdOverflow** [Hacker0x01/hacker101#10]
At about [03:10-ish](https://youtu.be/Zj6Z4QMzObE?t=3m13s), the final bullet point states:

> EVER USE ECB

That should be:

> NEVER USE ECB

![image](https://user-images.githubusercontent.com/18099289/35358401-d5c9a1aa-0156-11e8-9c40-fc7089135228.png)

**Comment by EdOverflow** [comment]
Don't mind the typo in the title.

![](http://www.reactiongifs.com/r/2013/06/hiding.gif)

**Comment by daeken** [comment]
This is actually not a typo, I just poorly designed the slide!  It says "Do Not" ... "EVER USE ECB".  I'll probably make this more clear in a future revision.
