### ISSUE TITLE
For new hackerone members

### ISSUE THREAD

**Issue by Ritesh12911** [Hacker0x01/hacker101#110]
First who wants to join takes the permission of other like the admin and me to admit in hackerone as a new member.

**Comment by MendelssohnTW** [comment]
I'm already a member of hackerone. I was able to figure it out. My email is
set up not to receive phishing. The message fell into SPAM. But I've been
able to work it out here.

Em ter., 11 de ago. de 2020 às 03:02, Ritesh12911 <notifications@github.com>
escreveu:
