### ISSUE TITLE
CTF level stuck on loading ...  https://ctf.hacker101.com/ctf/launch/2

### ISSUE THREAD

**Issue by Progressive-Programmer** [Hacker0x01/hacker101#155]
https://ctf.hacker101.com/ctf/launch/2
This level page is stuck in loading ... unable to Restart it again as well
Tried Restart several times but the issue is still there.   
This is happening since last two days. 
![Screenshot 2021-07-04 at 11 37 42 PM](https://user-images.githubusercontent.com/25490780/124395313-0c014080-dd21-11eb-8828-5e5a5c2840d0.png)

**Comment by Dragonaria123** [comment]
> https://ctf.hacker101.com/ctf/launch/2
> This level page is stuck in loading ... unable to Restart it again as well
> Tried Restart several times but the issue is still there.
> This is happening since last two days.
> ![Screenshot 2021-07-04 at 11 37 42 PM](https://user-images.githubusercontent.com/25490780/124395313-0c014080-dd21-11eb-8828-5e5a5c2840d0.png)

What did you do to fix it?

**Comment by mbeiranvand** [comment]
Scrinshot is a bad way

**Comment by mbeiranvand** [comment]
Over lab
