### ISSUE TITLE
CTF launching for flags never loads 

### ISSUE THREAD

**Issue by Bethuelas** [Hacker0x01/hacker101#156]
When in the ctf launch page it gets stuck on Launching and displays the message saying wait for a moment........ forever and the page never loads

**Comment by Bethuelas** [comment]
screenshot

**Comment by Bethuelas** [comment]
/root/Pictures/Screenshot from 2021-07-04 19:08:35.png

**Comment by captMM** [comment]
Same thing with me. I have tried different computers, networks as well.

I do sometimes get a Cloudflare error...

Error 520 Ray ID: 671ebd6fa84b2325

**Comment by captMM** [comment]
Working now. Maybe had something to do with the ongoing maintenance.
