### ISSUE TITLE
Kof 

### ISSUE THREAD

**Issue by kofstar** [Hacker0x01/hacker101#159]

**Comment by mbeiranvand** [comment]
Close you bakers , and only me manager cyber security deposit and automatic Control company me know

**Comment by mbeiranvand** [comment]
Send me info hacker, and make hacker new for me

**Comment by mbeiranvand** [comment]
[Ghods Niroo Engineering Company](https://www.ghods-niroo.com) 
This company Engineering is mc project prodect process, and please business by this company the wor

> ### 

- 

- [ ] _**``**_
