### ISSUE TITLE
remove dead link of priority queue incentive (RIP priority queue incentive?)

### ISSUE THREAD

**Issue by elvey** [Hacker0x01/hacker101#196]
Previous _remove dead links of priority queue incentive_ was incomplete.

https://www.hacker101.com/start-here has a dead link to what was
https://web.archive.org/web/20220525102609/https://docs.hackerone.com/hackers/invitations-priority-queue.html

I created https://github.com/Hacker0x01/hacker101/compare/master...elvey:hacker101:patch-1 but then I noticed there's already a pull request : pull #192.  But there isn't an issue, so I'm making this one. 

If https://github.com/Hacker0x01/docs.hackerone.com/commit/418622040b112ca9c4126c7d387c9e611f2642f0 was correct, this should be too - this was missed.  But is it correct? a) does it still exist, and b)"priority invitation queue" sounds more awkward to me than "priority invitation queue".

P.S. Issues 185 - 188 seem to be gibberish/spam.

**Comment by djwy** [comment]
Thanks for bringing this up!

We've updated this in https://github.com/Hacker0x01/hacker101/pull/200 with some slightly different language.
