### ISSUE TITLE
Links in the contents (navigation) table in the readme file are not working

### ISSUE THREAD

**Issue by dekadentno** [Hacker0x01/hacker101#20]
Links are giving a 404 because of the missing .md extension.
Example:
https://github.com/Hacker0x01/hacker101/blob/master/sessions/clickjacking
It should be:
https://github.com/Hacker0x01/hacker101/blob/master/sessions/clickjacking.md

**Comment by EdOverflow** [comment]
Yeah, I broke that, because the previous website was using the README.md file as the index file. I will submit a PR to fix this quickly.
