### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Shayre** [Hacker0x01/hacker101#31]
I have some suggestions and requests that have come through to the Support team:

1. For people that do not have access to the internet, all the time make some of the content available offline or downloadable.

2. Upload the following videos: 
Vulnerabilities Directory Traversal 
https://github.com/Hacker0x01/hacker101/blob/master/vulnerabilities/directory_traversal.md

Vulnerabilities Padding Oracle 
https://github.com/Hacker0x01/hacker101/blob/master/vulnerabilities/padding_oracle.md

Vulnerabilities Reflected Cross-Site Scripting (XSS) 
https://github.com/Hacker0x01/hacker101/blob/master/vulnerabilities/reflected_xss.md

Vulnerabilities Stored Cross-Site Scripting (XSS) 
https://github.com/Hacker0x01/hacker101/blob/master/vulnerabilities/stored_xss.md

Vulnerabilities Stream Cipher Key Reuse 
https://github.com/Hacker0x01/hacker101/blob/master/vulnerabilities/stream_reuse.md

3. Add a section about recon and basic methodology for recon. 

4. Add a section for resource material for reading.

**Comment by iNoSec** [comment]
I think you can/must start to search by yourslef all the material for reading you need to master google if you want to make something in "hacking"... like your 1st point , you can make it yourself an offline resources by copy the repo or wget the site, download videos with youtube-dl... and voila you have an offline copy of the site with videos etc (but you must modify some links to make them working locally, and like that you will learn more things too... not very to do with sed etc...)

**Comment by ArtemSer** [comment]
Maybe we could write some bash-file with git & youtube-dl for fun?
