### ISSUE TITLE
Videos in markup are showing as iframe code

### ISSUE THREAD

**Issue by Sluder** [Hacker0x01/hacker101#33]
All the videos under sessions are displaying the code for an embedded youtube video, could just have a link to clean up?
Or something like this: https://stackoverflow.com/questions/11804820/embed-a-youtube-video

Is this the same request as https://github.com/Hacker0x01/hacker101/pull/32 ?

**Comment by EdOverflow** [comment]
This is actually the source code for https://www.hacker101.com. The content is really meant to be viewed there, hence the embedded YouTube videos.

**Comment by boblinux** [comment]
![github](https://user-images.githubusercontent.com/10354951/36427393-648739d8-164d-11e8-9ff3-a4c292d9214c.PNG)
it's look lik that ...
