### ISSUE TITLE
Confusing Coursework

### ISSUE THREAD

**Issue by abdilahrf** [Hacker0x01/hacker101#39]
When i try this coursework : https://levels-a.hacker101.com/levels/0/

i know there is have csrf bug because i didn't see any prevention for csrf like token or something but i donno if i already solve it in correct way

and, i got the reflected xss in the amount parameter that can be send using get/post request : `https://levels-a.hacker101.com/levels/0/?to=1&amount=%22%3E%3Cimg%20src=x%20/%3E`
but there is no clue or something that indicate i solve the problem

also for the idor i think we could manipulate the id on parameter `to` but i confuse what the goal is from the idor, there must be something that indicate we got the vulnerability it will help new comers to learn the idea.

**Comment by spkellydev** [comment]
I second this!

**Comment by enzotrucchi** [comment]
Same!

**Comment by chadfurman** [comment]
I think it's less of a CTF and more of a can-you-find, and if you can great!  There aren't flag signals in the real world.  I could be wrong....

**Comment by abdilahrf** [comment]
the answer for this already here 
https://ctf.hacker101.com/howtoplay
