### ISSUE TITLE
Description is identical to the title : Hacker 101

### ISSUE THREAD

**Issue by w42ren** [Hacker0x01/hacker101#49]
The current repository description is identical to the name of the repository, this is not very informative when parsing the json reply from a repository search using the github api. I would recommend  adding  a short meaningful description,  for example:  "a free class for web security" .

**Comment by EdOverflow** [comment]
It might be worth changing it to:

> Hacker101 is a free online class for web security.

**Comment by countryfury** [comment]
I need help using it on android
