### ISSUE TITLE
Source to coursework

### ISSUE THREAD

**Issue by RuneStone0** [Hacker0x01/hacker101#54]
It would be great if you would open source the coursework, so you can review the code, add suggestions and host it locally. The site where the coursework is hosted, is every slow - throttled?

**Comment by daeken** [comment]
This is now public, thanks and happy hacking

**Comment by RuneStone0** [comment]
I only see the .md files ?

**Comment by martijnrusschen** [comment]
You can find the source here: https://github.com/Hacker0x01/Hacker101Coursework
