### ISSUE TITLE
Change order of agenda in SQLi lesson

### ISSUE THREAD

**Issue by alopresto** [Hacker0x01/hacker101#56]
The description and contents list the order of topics as "SQL injection (, blind SQLi) , directory traversal, and command injection" but the order covered in the video is "directory traversal, command injection, SQL injection, blind SQLi". Changing the order of the description and contents to be inline with the video order will help users understand the concepts and search within the video for specific sections.

**Comment by daeken** [comment]
Agreed, these should match whenever possible.  I'll look into this ASAP.  Thanks!

**Comment by amogh0503** [comment]
We want to some way to apply our newly learned skills to be implemented simultaneously
