### ISSUE TITLE
Coursework source code after 1st october

### ISSUE THREAD

**Issue by iNoSec** [Hacker0x01/hacker101#59]
Hi and thank you for all you share here!! thats a lot of work and you make it well!!!

We can read the coursework will be deprecated on the 1st October in favor of the CTF but can you release the source code in this github for those who want to make them locally, or just want to review the code for trainning our skill in code analysis??
Thanks

**Comment by daeken** [comment]
The source code is now public, thanks for your interest and happy hacking
