### ISSUE TITLE
Can you please provide downloadable urls of these videos for ones have no access to youtube

### ISSUE THREAD

**Issue by 2071283913** [Hacker0x01/hacker101#72]
I have made a lot effort to try to visit youtube but failed. 

I wonder that will you please provide urls for these videos that i can download and learn them.

Best wishes.

**Comment by 2071283913** [comment]
Here is a shell script that i try to download all videos with youtube-dl, but failed with the poor network connection.

<script src="https://gist.github.com/2071283913/43e443dcd96442abe04a5f2f70872ed6.js"></script>

**Comment by MilindPurswani** [comment]
I think that would be really great, since some countries do prohibit access to YouTube content. Hackers in those countries will be greatly benefited if they are provided access to these videos from a secondary content provider, or perhaps storing videos in an s3 bucket won't be a bad idea.

**Comment by zsdevX** [comment]
+1

**Comment by mayankmetha** [comment]
+1

**Comment by Btechgautam** [comment]
Hello all,

Hope everyone is safe.
This is Gautam Krishnan from Chennai.
I am looking for a job in Cyber Security.
I am a fresher with Internship experience and self learning into Cyber
Security.
I have completed courses like CEH CCNA(Only completed the course content
and not certification) and currently working on OSCP.
Any help this moment would be highly appreciated. If there is any opening
kindly let me know.


*Regards,*


*Gautam*

*reachgautamkrishnan@gmail.com <reachgautamkrishnan@gmail.com>*

**Comment by VaeterchenFrost** [comment]
With for example https://unblockvideos.com/youtube-video-restriction-checker/ it would be possible to check the restrictions.

Then I notice that some videos are called like 
*resources/08_android_hacking_tools.md* : https://www.youtube.com/watch?v=y0O3sCX9ftM

And some inline like 
*sessions/threat_modeling.md* : `<iframe id="ytplayer" type="text/html" width="640" height="360" src="https://www.youtube-nocookie.com/embed/6DI7RIXUTg8?rel=0&autoplay=0&origin={{ site.url }}"` ...

**Comment by VaeterchenFrost** [comment]
It might be helpful if @2071283913 could provide some info what was tried, and with which videos there are problems.

**Comment by 1islammahfuZ** [comment]
> I have made a lot effort to try to visit youtube but failed.
> 
> I wonder that will you please provide urls for these videos that i can download and learn them.
> 
> Best wishes.

Tnx

**Comment by sparkofwisdom** [comment]
generate downloadable urls of these videos for ones have no access to youtube

**Comment by PrincessEclipse** [comment]
This is a great thing to have. I like it!

**Comment by tomdev** [comment]
The links to YouTube videos are available in the source code; you can probably use online YouTube download websites to download these directly.

We do not plan on supporting direct download links.
