### ISSUE TITLE
Incorrect "sign up now" link on CTF "how to play" page

### ISSUE THREAD

**Issue by gallexi** [Hacker0x01/hacker101#75]
Hi! Thanks for this content!

I just noticed that the "sign up now" link in the "get started" section of this page: https://ctf.hacker101.com/howtoplay points to stay on that page (/howtoplay), instead of pointing to the "sign up now" page.

Hope this helps!

**Comment by Prashles** [comment]
This appears to be fixed now. Closing. 

Thanks
