### ISSUE TITLE
Error while running 'bundle install' in directory.

### ISSUE THREAD

**Issue by vip2111** [Hacker0x01/hacker101#78]
Error while running 'bundle install' in directory.

_Originally posted by @hackgod512 in https://github.com/Hacker0x01/hacker101/issues/76#issuecomment-491386777_

**Comment by pappanunny** [comment]
What is the error you get? Could you provide more information on it?

**Comment by Willianvdv** [comment]
If you got the same error as #76, try this: https://github.com/bundler/bundler/issues/6227#issuecomment-464730194

**Comment by Ricciflow** [comment]
Thanks！





------------------ Original ------------------
