### ISSUE TITLE
uildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by eedegithub** [Hacker0x01/hacker101#84]
![image](https://user-images.githubusercontent.com/26837866/71833382-bd50f700-30e7-11ea-928d-ad4ed43f3a33.png)
what‘s the problem

**Comment by Willianvdv** [comment]
It's hard to tell as this is only a fragment of the error, can you post the whole error?

**Comment by tayyabali785** [comment]
ok

**Comment by eedegithub** [comment]
In the project directory, run:&nbsp; &nbsp;bundle install





thanks for tell me why this is the case




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Willian van der Velde"<notifications@github.com&gt;; 
发送时间: 2020年1月9日(星期四) 晚上11:22
收件人: "Hacker0x01/hacker101"<hacker101@noreply.github.com&gt;; 
抄送: "1729661969"<1729661969@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Hacker0x01/hacker101] uildError: ERROR: Failed to build gem native extension. (#84)




It's hard to tell as this is only a fragment of the error, can you post the whole error?

**Comment by hakoo361** [comment]
How I hack someone Facebook password

**Comment by Willianvdv** [comment]
just email Mark, he will send you the password
